spring.application.name=flashflow
spring.profiles.include=db,redis,kafka,outbox,server

# JWT Configuration
flashflow.jwt.secret=${JWT_SECRET:MyJwtseCreTEsECRETe123Withproper&length#and_embeded)with*special^CHAr}

